### ISSUE TITLE
Need documentation / examples using artifact names

### ISSUE THREAD

**Issue by aittalam** [mozilla-ai/lm-buddy#47]
The model artifact from a tuning is `run_name-model`, which means that if you want to load a model for an eval (e.g. lm-harness) where the run will be updated with eval results, you have to write the following:

```
model:
  load_from:
    name: "Mistral-7B-Instruct-v0.2-20240212-model" ### NOTE the "-model" suffix here
    project: "davide-testing-flamingo"
    entity: "mozilla-ai"
...
# Tracking info for where to log the run results
tracking:
  name: "Mistral-7B-Instruct-v0.2-20240212"
  project: "davide-testing-flamingo"
  entity: "mozilla-ai"
```

I think this is ok, but we might want to document it or put it into our examples/tutorials.

Also, all artifacts have a fixed name which is f"{run_name}-{artifact_type}". I currently do not see the need to allow for custom artifact names, but wanted to check your opinion on this.
