### ISSUE TITLE
lm-harness `IndexError: list index out of range` due to missing  `bnb_4bit_compute_dtype` 

### ISSUE THREAD

**Issue by aittalam** [mozilla-ai/lm-buddy#48]
The quantization parameter `bnb_4bit_compute_dtype` seem to be optional for fine-tuning, but when we run lm-harness we get an error if it is not specified in the config. 

Example: http://10.145.91.219:8265/#/jobs/raysubmit_RvS6DHdgeMPYQjW9

Solution: the code runs properly if we add the parameter to the config, e.g.
```
quantization:
  load_in_4bit: True
  bnb_4bit_quant_type: "fp4"
  bnb_4bit_compute_dtype: "bfloat16"
```

Shall we always put a default value (e.g. `bfloat16`) or just document it to make sure it is specified when needed?
